#!/usr/bin/env python3
"""Build the site from stories.json.

stories.json is the single source of truth. This script writes:

  index.html                  the app page (STORIES + inlined covers regenerated)
  stories/index.html          a plain index of every story
  stories/<slug>/index.html   one crawlable page per story (OG tags, canonical, cover)
  sitemap.xml, robots.txt     so search engines can find those pages

Why generate: one story URL per story is the difference between "an app in a browser"
and a site people can find and share. Adding a story = append to stories.json, re-run.

  ./scripts/build-site.py            # regenerate everything
  ./scripts/build-site.py --check    # report drift/duplicates, write nothing
"""
import base64
import html
import json
import pathlib
import re
import sys
import urllib.parse
from datetime import datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://yanbing2026.github.io/story-twirl"
PREFIX = urllib.parse.urlsplit(SITE).path.rstrip("/")   # "" on a custom domain
STORIES = ROOT / "stories.json"
BEGIN = "/* STORIES:BEGIN"
END = "/* COVERS:END */"

CSS = """
:root{--bg:#1b1436;--bg2:#241a4a;--card:#2c2158;--ink:#f4f1ff;--dim:#b9aee6;--accent:#ffd166;--accent2:#7ee0c1;--line:#3d2f70}
*{box-sizing:border-box}
body{margin:0;background:linear-gradient(170deg,var(--bg),var(--bg2) 60%,#150f2c);color:var(--ink);
  font:18px/1.7 ui-rounded,"Segoe UI",system-ui,-apple-system,sans-serif;min-height:100%}
.wrap{max-width:680px;margin:0 auto;padding:22px 20px 60px}
a{color:var(--accent2)}
header a{color:var(--dim);text-decoration:none;font-size:15px;letter-spacing:.3px}
h1{font-size:30px;line-height:1.2;margin:14px 0 6px}
.meta{color:var(--dim);font-size:14px;margin-bottom:18px}
img.cover{display:block;width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:14px;margin:0 0 22px;background:#150f2c}
p{margin:0 0 16px}
.lesson{background:#1a1236;border-left:3px solid var(--accent2);border-radius:10px;padding:14px 16px;margin:24px 0}
.lesson b{color:var(--accent2)}
.cta{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:18px;margin:26px 0}
.cta a.btn{display:inline-block;background:var(--accent);color:#2a1c00;font-weight:650;border-radius:999px;
  padding:12px 20px;text-decoration:none;margin-top:10px}
footer{margin-top:30px;color:var(--dim);font-size:14px;text-align:center}
ul.index{list-style:none;padding:0}
ul.index li{margin:14px 0;background:var(--card);border:1px solid var(--line);border-radius:14px;overflow:hidden}
ul.index a{display:block;text-decoration:none;color:var(--ink)}
ul.index img{display:block;width:100%;aspect-ratio:16/9;object-fit:cover}
ul.index .txt{padding:12px 14px}
ul.index small{color:var(--dim)}
"""


def esc(s):
    return html.escape(s, quote=True)


def plain(s):
    """Resolve the personalisation placeholders for a static, nameless page."""
    return s.replace("{{namePos}}", "your child's").replace("{{name}}", "your child")


def load():
    stories = json.loads(STORIES.read_text())
    seen = set()
    for s in stories:
        if s["slug"] in seen:
            raise SystemExit(f"duplicate slug: {s['slug']}")
        seen.add(s["slug"])
        for k in ("id", "slug", "title", "blurb", "minutes", "cover", "lesson", "body"):
            if k not in s:
                raise SystemExit(f"{s.get('slug')}: missing field {k}")
        # Contract: body is a FLAT list of paragraph strings, and the app renders s.body.
        # (It used to be [[...]] and a regenerated block silently broke openStory.)
        if not (isinstance(s["body"], list) and s["body"]
                and all(isinstance(p, str) for p in s["body"])):
            raise SystemExit(f"{s['slug']}: body must be a non-empty list of paragraph strings")
    return stories


def covers_inlined(stories):
    out = {}
    for s in stories:
        p = ROOT / s["cover"]
        out[s["id"]] = "data:image/webp;base64," + base64.b64encode(p.read_bytes()).decode()
    return out


def build_stamp():
    """Short sha + date, so 'did the site update?' is answerable without asking anyone."""
    import subprocess
    try:
        sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                             capture_output=True, text=True, timeout=5).stdout.strip()
    except Exception:
        sha = ""
    return f"{sha or 'nogit'} {datetime.now().strftime('%Y-%m-%dT%H:%M')}"


def build_short():
    """What the status line shows: the moment of the build, so 'did it refresh?'
    needs no sha comparison."""
    return datetime.now().strftime("%m-%d %H:%M")


def app_block(stories):
    """The generated JS data block inside index.html."""
    lines = [f"{BEGIN} — generated by scripts/build-site.py from stories.json; do not hand-edit */",
             f"const BUILD = {json.dumps(build_short())};",
             "const STORIES = ["]
    for s in stories:
        body = json.dumps(s["body"], ensure_ascii=False, indent=1).replace("\n", "\n ")
        lines.append(" {")
        lines.append(f"  id: {json.dumps(s['id'])}, title: {json.dumps(s['title'], ensure_ascii=False)},")
        lines.append(f"  blurb: {json.dumps(s['blurb'], ensure_ascii=False)}, minutes: {s['minutes']},")
        lines.append(f"  body: {body},")
        lines.append(f"  lesson: {json.dumps(s['lesson'], ensure_ascii=False)}")
        lines.append(" },")
    lines.append("];")
    lines.append("const COVERS = {")
    for sid, uri in sorted(covers_inlined(stories).items()):
        lines.append(f"  {sid}: '{uri}',")
    lines.append("};")
    lines.append(END)
    return "\n".join(lines)


def build_app(stories):
    html_src = (ROOT / "index.html").read_text()
    # Match from the BEGIN marker, not from `const STORIES = [`, or anything the
    # generator writes above that line (the BUILD stamp) accumulates on every run.
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html_src):
        raise SystemExit("index.html: could not find the generated STORIES/COVERS region")
    new = pat.sub(lambda _: app_block(stories), html_src, count=1)
    (ROOT / "index.html").write_text(new)
    return len(html_src), len(new)


def page(title, desc, canonical, body, og_image=None):
    og = f'<meta property="og:image" content="{SITE}/{og_image}">' if og_image else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="theme-color" content="#1b1436">
<meta name="build" content="{build_stamp()}">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<link rel="canonical" href="{canonical}">
<meta property="og:type" content="article">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{canonical}">
{og}
<meta name="twitter:card" content="summary_large_image">
<style>{CSS}</style>
</head>
<body>
<div class="wrap">
{body}
</div>
</body>
</html>
"""


def story_page(s, stories):
    paras = "\n".join(f"<p>{esc(plain(p))}</p>" for p in s["body"])
    others = [o for o in stories if o["slug"] != s["slug"]]
    more = "".join(
        f'<li><a href="{PREFIX}/stories/{o["slug"]}/"><img src="{SITE}/{o["cover"]}" alt="">'
        f'<div class="txt"><b>{esc(o["title"])}</b><br><small>{esc(o["blurb"])}</small></div></a></li>'
        for o in others)
    body = f"""<header><a href="{PREFIX}/">← Story Twirl</a></header>
<h1>{esc(s["title"])}</h1>
<div class="meta">{s["minutes"]} min read · ages 3–6 · bedtime story</div>
<img class="cover" src="{PREFIX}/{s["cover"]}" alt="{esc(s["title"])} illustration">
{paras}
<div class="lesson"><b>One question for afterwards:</b> {esc(plain(s["lesson"]["ask"]))}<br><br>
<b>Did you know?</b> {esc(plain(s["lesson"]["fact"]))}</div>
<div class="cta">In the app this story reads itself aloud — offline, in the phone's own voice — and it can
use your child's name instead of “your child”. One story every night is free.
<a class="btn" href="{PREFIX}/">Open Story Twirl</a></div>
<h2 style="font-size:20px">More stories</h2>
<ul class="index">{more}</ul>
<footer>Story Twirl · a story a night · build {build_short()}</footer>"""
    desc = f'{s["title"]}: {plain(s["blurb"])} A {s["minutes"]}-minute bedtime story for ages 3–6.'
    return page(s["title"], desc, f"{SITE}/stories/{s['slug']}/", body, og_image=s["cover"])


def index_page(stories):
    items = "".join(
        f'<li><a href="{PREFIX}/stories/{s["slug"]}/"><img src="{PREFIX}/{s["cover"]}" alt="">'
        f'<div class="txt"><b>{esc(s["title"])}</b><br><small>{esc(s["blurb"])} · {s["minutes"]} min</small></div></a></li>'
        for s in stories)
    body = f"""<header><a href="{PREFIX}/">← Story Twirl</a></header>
<h1>Bedtime stories</h1>
<div class="meta">{len(stories)} stories · ages 3–6 · one free a night in the app</div>
<ul class="index">{items}</ul>
<footer>Story Twirl · a story a night · build {build_short()}</footer>"""
    return page("Bedtime stories for ages 3–6 — Story Twirl",
                "Short bedtime stories for children aged 3–6, each with a question to talk about afterwards.",
                f"{SITE}/stories/", body)


def sitemap(stories):
    today = datetime.now().strftime("%Y-%m-%d")
    urls = [f"{SITE}/", f"{SITE}/stories/"] + [f"{SITE}/stories/{s['slug']}/" for s in stories]
    entries = "".join(
        f"  <url><loc>{u}</loc><lastmod>{today}</lastmod></url>\n" for u in urls)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
            f"{entries}</urlset>\n")


def main():
    stories = load()
    check = "--check" in sys.argv
    if check:
        print(f"stories.json: {len(stories)} stories, slugs unique")
        for s in stories:
            missing = [s["cover"]] if not (ROOT / s["cover"]).exists() else []
            print(f"  {s['slug']:<40} {len(s['body'])} paragraphs"
                  + (f"  MISSING {missing}" if missing else ""))
        return 0

    before, after = build_app(stories)
    out = [f"index.html {before // 1024}KB -> {after // 1024}KB (data block regenerated)"]

    (ROOT / "stories").mkdir(exist_ok=True)
    (ROOT / "stories/index.html").write_text(index_page(stories))
    for s in stories:
        d = ROOT / "stories" / s["slug"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "index.html").write_text(story_page(s, stories))
        out.append(f"stories/{s['slug']}/index.html")
    (ROOT / "sitemap.xml").write_text(sitemap(stories))
    (ROOT / "robots.txt").write_text(f"User-agent: *\nAllow: /\nSitemap: {SITE}/sitemap.xml\n")
    out.append("sitemap.xml, robots.txt")
    print("\n".join("  " + l for l in out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
