#!/usr/bin/env python3
"""Embed story covers into index.html as data URIs.

Why data URIs: the same HTML is served by the website AND dropped into the APK's
assets, where a relative <img src> is a cross-origin file:// load the WebView may
refuse. Inlining removes that whole class of failure and keeps the product one file.

Idempotent: rewrites only the COVERS block, regenerated from img/*.webp.

  ./scripts/embed-covers.py            # embed every img/cover-<id>.webp
  ./scripts/embed-covers.py --check    # report which stories have covers, no write
"""
import base64
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HTML = ROOT / "index.html"
IMG = ROOT / "img"
BEGIN = "/* COVERS:BEGIN"
END = "/* COVERS:END */"


def covers():
    out = {}
    for p in sorted(IMG.glob("cover-*.webp")):
        sid = p.stem[len("cover-"):]
        out[sid] = "data:image/webp;base64," + base64.b64encode(p.read_bytes()).decode()
    return out


def story_ids():
    ids = set()
    in_stories = False
    for line in HTML.read_text().splitlines():
        if line.startswith("const STORIES"):
            in_stories = True
        if in_stories:
            m = re.match(r"\s*id:'([^']+)'", line)
            if m:
                ids.add(m.group(1))
        if in_stories and line.startswith("];"):
            break
    return ids


def main():
    html = HTML.read_text()
    have = covers()
    ids = story_ids()
    missing = sorted(ids - set(have))
    extra = sorted(set(have) - ids)

    for sid, uri in have.items():
        print(f"  {sid}: {len(uri) // 1024}KB embedded")
    if missing:
        print(f"  no cover yet (renders without image): {', '.join(missing)}")
    if extra:
        print(f"  WARNING cover with no story: {', '.join(extra)}")

    if "--check" in sys.argv:
        return 0

    body = "const COVERS = {\n" + "".join(
        f"  {sid}: '{uri}',\n" for sid, uri in sorted(have.items())) + "};"
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        print("ERROR: COVERS markers not found in index.html")
        return 1
    new = pat.sub(BEGIN + " (generated by scripts/embed-covers.py from img/*.webp — do not hand-edit) */\n"
                  + body + "\n" + END, html, count=1)
    HTML.write_text(new)
    print(f"index.html: {len(html) // 1024}KB -> {len(new) // 1024}KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
